name: hondooye_logger
description: A useful logger.
version: 1.0.0
repository: https://github.com/Doohyeon-Kim/hondooye-logger

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  logger: ^2.0.0
  http: ^1.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter: